name: pokemon_test_case
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Annotations
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Routing
  auto_route: ^5.0.4

  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^2.1.0

  # Bloc
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1

  # Network
  dio: ^5.0.2
  retrofit: ^4.0.1
  connectivity_plus: ^3.0.3

  # Icons
  cupertino_icons: ^1.0.2
  simple_animations: ^5.0.0+3

dev_dependencies:
  # Tests
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  mocktail: ^0.3.0

  # Code generation
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.1.4
  retrofit_generator: ^6.0.0+1

  # Static analysis
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.6.0

flutter:
  assets:
    - graphics/images/splash_img.jpg
    - graphics/images/random_pokemon_img.jpg
    - graphics/images/get_pokemon_img.png
    - graphics/images/error_img.png
  uses-material-design: true

